name: flutter_heatmap_calendar_fr
description: Just forked flutter_heatmap_calendar to make it french
version: 1.0.5
homepage: https://github.com/fodil-a/flutter_heatmap_calendar

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
